### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by Oghenebrume50** [ybadmus/Embedding-Images-and-Video#2]
Hi team good work on your first project, you guys did well, but missed some little details in the instructions.
Firstly, you only submit a pull request link, not the repository link.
secondly, never merge to master until the project has been approved.
So, in this case, you guys should have submitted the pull request link from homepage branch to master branch.
Now to the code implementation issues.
- Use  <button> tag for the search button, not  <a> 
- The navbar should have at least three embedded images on the rightmost part of it. check the original page for clarity.
- Add the comment section
- Validate HTML and correct all errors and warnings.

Please fix these things and submit for re-review, make sure to submit the pull request link for the next review, kudos for a good start

**Comment by konyan** [comment]
@Oghenebrume50  i am done in fixing all issues list. Please check and feedback to me. Thanks.
